# accel-ppp — SSTP pour clients MikroTik (nanoTECH VPN)
[modules]
log_file
sstp
chap_secrets
ippool
shaper

[core]
thread-count=2

[log]
log-file=/var/log/accel-ppp/accel-ppp.log
log-level=3

[ppp]
verbose=1
min-mtu=1280

[sstp]
bind=0.0.0.0
port=SSTP_PORT_PLACEHOLDER
ssl-pemfile=/etc/nanotech-vpn/sstp/server.pem
ssl-keyfile=/etc/nanotech-vpn/sstp/server.key
ppp-max-mtu=1452

[cli]
telnet=127.0.0.1:2001

[ip-pool]
gw-ip-address=10.200.101.1

[chap-secrets]
gw-ip-address=10.200.101.1
chap-secrets=/etc/nanotech-vpn/accel-chap-secrets
